### ISSUE TITLE
Rider sometimes has problems importing the correct dependency

### ISSUE THREAD

**Issue by AldeRoberge** [JohnBaracuda/Thread-Dispatcher#1]
Hey, first of all this is an awesome tool that has replaced all of the botched main thread schedulers I have ever wrote.

For some reason, Rider sometimes just can't import the dependency to Dispatcher. This happens : 

![image](https://github.com/JohnBaracuda/com.baracuda.thread-dispatcher/assets/4276275/8b3c27fe-53fc-4fef-ad4a-0db7ce62140a)

And all 3 choices do nothing. Would you happen to know why this happens? It only happens rarely, and with this class specifically.

**Comment by JohnBaracuda** [comment]
It seems you might be missing an assembly reference. I've noticed that Rider can suggest types from assemblies not currently referenced but sometimes fails to automatically add these references. Since the dispatcher is located in its own assembly, it is automatically referenced by the default Assembly-CSharp. However, if you're working within a script that's part of a different assembly, you might need to manually add the dependency.

As a side note: You cannot use the new operator to create an instance of the Dispatcher class since it inherits from MonoBehaviour.

**Comment by AldeRoberge** [comment]
![image](https://github.com/JohnBaracuda/com.baracuda.thread-dispatcher/assets/4276275/dcee50cd-38c6-4334-8865-2589008429f6)

For some reason, this is perfectly fine with Unity (no errors in console), but Rider insists that there's an error.

I am not using assembly definitions in this project (script is located in 'Player').

I will close this issue as it is probably just a Rider bug. Thanks for your time!

**Comment by JohnBaracuda** [comment]
If this is the case, I assume the issue isn't with Unity or the plugin, but rather with Rider. I've had similar situations before where Rider indicated a problem, even though Unity showed none. Here are some things that helped me before:

- Regenerate your project files.
- Alternatively, you can manually delete your .csproj files in your project folder. (Ensure both Rider and Unity are closed before doing this.)"
- Check if there is some linking issue between Unity, The Rider Plugin and Rider
- If none of this works you might find some help with google or on the public Unity or Rider Forums.
